//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetINK.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetINK.Common.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active round cannot be removed!.
        /// </summary>
        public static string msgActiveRoundCannotBeRemoved {
            get {
                return ResourceManager.GetString("msgActiveRoundCannotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betting all matches is required!.
        /// </summary>
        public static string msgBetAllMatches {
            get {
                return ResourceManager.GetString("msgBetAllMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose at lease one league.
        /// </summary>
        public static string msgChooseLeague {
            get {
                return ResourceManager.GetString("msgChooseLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identity details..
        /// </summary>
        public static string msgInvalidIdentityDetails {
            get {
                return ResourceManager.GetString("msgInvalidIdentityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active season yet, you cannot add new round now!.
        /// </summary>
        public static string msgNoActiveSeasonsFound {
            get {
                return ResourceManager.GetString("msgNoActiveSeasonsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active season yet!.
        /// </summary>
        public static string msgNoActiveSeasonYet {
            get {
                return ResourceManager.GetString("msgNoActiveSeasonYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to add matches for this round!.
        /// </summary>
        public static string msgNotAllowedToAddMatchForThisRound {
            get {
                return ResourceManager.GetString("msgNotAllowedToAddMatchForThisRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to edit this match!.
        /// </summary>
        public static string msgNotAllowedToEditMatch {
            get {
                return ResourceManager.GetString("msgNotAllowedToEditMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to edit this round!.
        /// </summary>
        public static string msgNotAllowedToEditRound {
            get {
                return ResourceManager.GetString("msgNotAllowedToEditRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing season with rounds related is not allowed..
        /// </summary>
        public static string msgRemovingSeasonNotAllowed {
            get {
                return ResourceManager.GetString("msgRemovingSeasonNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} added to the {1} role..
        /// </summary>
        public static string msgSuccessAddedToRole {
            get {
                return ResourceManager.GetString("msgSuccessAddedToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added!.
        /// </summary>
        public static string msgSuccessfullyAdded {
            get {
                return ResourceManager.GetString("msgSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited!.
        /// </summary>
        public static string msgSuccessfullyEdited {
            get {
                return ResourceManager.GetString("msgSuccessfullyEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your predictions are successfully added, good luck!.
        /// </summary>
        public static string msgSuccessfulPredictions {
            get {
                return ResourceManager.GetString("msgSuccessfulPredictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} removed from {1} role..
        /// </summary>
        public static string msgSuccessRemovedFromRole {
            get {
                return ResourceManager.GetString("msgSuccessRemovedFromRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team cannot play against itself..
        /// </summary>
        public static string msgTeamDuplicate {
            get {
                return ResourceManager.GetString("msgTeamDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} already in role {1}..
        /// </summary>
        public static string msgUserAlreadyInRole {
            get {
                return ResourceManager.GetString("msgUserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} not in role {1}..
        /// </summary>
        public static string msgUserNotInRole {
            get {
                return ResourceManager.GetString("msgUserNotInRole", resourceCulture);
            }
        }
    }
}
